os: osx
osx_image: xcode11.3
language: swift

cache:
directories:

install:
- bundle install --path .
# - brew install danger/tap/danger-swift

script:
# - bundle exec fastlane custom_lane --verbose
- bundle exec danger
# - danger-swift ci

after_success: 
  # - bundle exec danger
  # - slather