os: osx
osx_image: xcode11.3
language: swift

cache:
  directories:
    - .build
    - ~/.danger-swift

install:
  - bundle install --path .
  # - gem install bundler
  # - bundle install
  - npm install -g danger
  # - swift package generate-xcodeproj

  # - brew install swiftlint
  # - brew install danger/tap/danger-swift

script:
  - set -o pipefail
  # - bundle exec fastlane run_testes --verbose
  # - danger-swift ci
  - xcodebuild -project TravisBot.xcodeproj -scheme TravisBot -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' test | xcpretty
  - swift run danger-swift ci


after_success: 
  # - bundle exec danger