os: osx
osx_image: xcode11.3
language: swift

cache:
directories:

install:
  - bundle install --path .

script:
  - set -o pipefail
  - bundle exec fastlane custom_lane --verbose

after_success: 
  - bundle exec danger