

default_platform(:ios)

platform :ios do

  before_all do
  end

  desc "Runs all the tests"
  lane :run_testes do
    scan(
      project: "TravisBot.xcodeproj",
      scheme: "TravisBot",
      clean: true,
      code_coverage: true,
      skip_build: true
    )
  end

  desc "Runs all the tests"
  lane :run_code_coverage do
    xcov(
      project: "TravisBot.xcodeproj",
      scheme: "TravisBot",
      exclude_targets: 'TravisBot.app',
      include_test_targets: true,
      # only_project_targets: true
    )

  danger
  end
end
